# GitGuardian configuration file
# https://docs.gitguardian.com/internal-repositories/configuration/ignored-matches

version: v1

# Exclude common test patterns that are not actual secrets
exclude:
  # Test files and directories
  paths:
    - "**/*test*/**"
    - "**/*.test.*"
    - "**/*.spec.*"
    - "**/test/**"
    - "**/tests/**"
    - "**/spec/**"
    - "**/fixtures/**"
    - "**/mocks/**"
    - "**/coverage/**"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.git/**"

# Allow specific patterns in test files
policies:
  - policy_name: "Test Password Patterns"
    ignored_matches:
      - match: "TestPassword123"
        reason: "Test password for unit tests"
      - match: "TestPass123"
        reason: "Test password for unit tests"
      - match: "Test1234"
        reason: "Minimum test password"
      - match: "TEST123"
        reason: "Test password validation"
      - match: "test123"
        reason: "Test password validation"
      - match: "TestPass"
        reason: "Test password validation"
      - match: "Password123"
        reason: "Test password for unit tests"
      - match: "DifferentTest123"
        reason: "Test password for comparison tests"
      - match: "ModifiedTest123"
        reason: "Test password for immutability tests"

# Specific secret types to look for
secret_types:
  - api_key
  - database_url
  - private_key
  - aws_access_key
  - github_token
  - jwt_secret
  - encryption_key
  
# Minimum entropy threshold for generic secrets
minimum_entropy: 3.5