packages:
  - "apps/**"
  - "packages/**"
  - "!libs/**"
  - "!a4co-ddd-microservices/**"

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@sentry/profiling-node'
  - bcrypt
  - esbuild
  - nx
  - prisma
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver
