packages:
  # Frontend applications
  - 'apps/frontend'
  - 'apps/dashboard-client'
  - 'apps/dashboard-web'

  # Canonical backend services
  - 'apps/services/*'
  - 'apps/infrastructure/*'

  # Auxiliary services still under active development
  - 'apps/transportista-service'

  # Shared packages
  - 'packages/**'

  # Explicitly exclude legacy/duplicate service locations
  - '!apps/notification-service/**'

  # Exclude frozen skeleton services from workspace resolution
  - '!apps/chat-service/**'
  - '!apps/analytics-service/**'
  - '!apps/artisan-service/**'
  - '!apps/cms-service/**'
  - '!apps/event-service/**'
  - '!apps/geo-service/**'
  - '!apps/loyalty-service/**'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@sentry/profiling-node'
  - bcrypt
  - esbuild
  - nx
  - prisma
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver
