name: 🚀 Build & Publish Docker Images (Dev)

on:
  push:
    branches: [ ci/github-actions ]
  workflow_dispatch:

jobs:
  build-and-push:
    name: 🧱 Build & Push to GHCR (Dev)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: Neiland85/a4co-ddd-microservices

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 🧩 Install pnpm
        run: npm install -g pnpm

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧱 Build & Push Frontend (Vite)
        uses: docker/build-push-action@v6
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend:dev
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend:${{ github.sha }}

      - name: 🧱 Build & Push Dashboard (Next.js)
        uses: docker/build-push-action@v6
        with:
          context: ./apps/dashboard-client
          file: ./apps/dashboard-client/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/dashboard:dev
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/dashboard:${{ github.sha }}

      - name: ✅ Summary
        run: |
          echo "✅ Imágenes dev subidas:"
          echo " - ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend:dev"
          echo " - ghcr.io/${{ env.IMAGE_NAMESPACE }}/dashboard:dev"
