"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Header;
const jsx_runtime_1 = require("react/jsx-runtime");
const image_1 = __importDefault(require("next/image"));
const link_1 = __importDefault(require("next/link"));
const button_1 = require("@/components/ui/button");
const lucide_react_1 = require("lucide-react");
function Header() {
    return ((0, jsx_runtime_1.jsx)("header", { className: "shadow-natural-sm sticky top-0 z-40 w-full border-b bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60", children: (0, jsx_runtime_1.jsx)("div", { className: "container mx-auto px-4 sm:px-6 lg:px-8", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex h-16 items-center justify-between", children: [(0, jsx_runtime_1.jsx)(link_1.default, { href: "/", className: "flex items-center space-x-2", children: (0, jsx_runtime_1.jsx)("div", { className: "relative h-10 w-24 drop-shadow-sm", children: (0, jsx_runtime_1.jsx)(image_1.default, { src: "/images/logo-green.jpeg", alt: "A4CO - Mercado Local de Ja\u00E9n", fill: true, className: "object-contain", priority: true }) }) }), (0, jsx_runtime_1.jsxs)("nav", { className: "hidden items-center space-x-8 md:flex", children: [(0, jsx_runtime_1.jsx)(link_1.default, { href: "/artesanos", className: "hover:text-a4co-olive-600 text-sm font-medium text-gray-700 transition-colors", children: "Artesanos" }), (0, jsx_runtime_1.jsx)(link_1.default, { href: "/productos", className: "hover:text-a4co-olive-600 text-sm font-medium text-gray-700 transition-colors", children: "Productos" }), (0, jsx_runtime_1.jsx)(link_1.default, { href: "/sobre-nosotros", className: "hover:text-a4co-olive-600 text-sm font-medium text-gray-700 transition-colors", children: "Sobre Nosotros" }), (0, jsx_runtime_1.jsx)(link_1.default, { href: "/contacto", className: "hover:text-a4co-olive-600 text-sm font-medium text-gray-700 transition-colors", children: "Contacto" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-4", children: [(0, jsx_runtime_1.jsxs)(button_1.Button, { variant: "ghost", size: "sm", className: "hover:shadow-natural-sm hidden transition-shadow sm:flex", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.User, { className: "mr-2 h-4 w-4" }), "Iniciar Sesi\u00F3n"] }), (0, jsx_runtime_1.jsxs)(button_1.Button, { size: "sm", className: "from-a4co-olive-500 to-a4co-clay-500 hover:from-a4co-olive-600 hover:to-a4co-clay-600 shadow-mixed hover:shadow-mixed-lg bg-gradient-to-r text-white transition-all duration-300", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.ShoppingBag, { className: "mr-2 h-4 w-4" }), (0, jsx_runtime_1.jsx)("span", { className: "hidden sm:inline", children: "Vender" })] }), (0, jsx_runtime_1.jsx)(button_1.Button, { variant: "ghost", size: "sm", className: "hover:shadow-natural-sm transition-shadow md:hidden", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Menu, { className: "h-4 w-4" }) })] })] }) }) }));
}
//# sourceMappingURL=header.js.map