'use client';
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Footer = Footer;
const jsx_runtime_1 = require("react/jsx-runtime");
const framer_motion_1 = require("framer-motion");
function Footer() {
    return ((0, jsx_runtime_1.jsxs)(framer_motion_1.motion.footer, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { duration: 0.5, delay: 0.2 }, className: "relative overflow-hidden border-t border-gray-200/60 bg-white/70 py-6 backdrop-blur-sm", children: [(0, jsx_runtime_1.jsxs)("div", { className: "opacity-4 pointer-events-none absolute inset-0", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-0 left-0 h-1 w-full bg-gradient-to-r from-amber-600/40 via-transparent to-pink-500/30" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute right-0 top-0 h-full w-32 bg-gradient-to-l from-yellow-50/60 to-transparent" })] }), (0, jsx_runtime_1.jsx)("div", { className: "container relative z-10 mx-auto px-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col items-center justify-between md:flex-row", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-sm text-gray-600", children: "\u00A9 2024 A4CO Dashboard. Todos los derechos reservados." }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-4 flex items-center space-x-6 md:mt-0", children: [(0, jsx_runtime_1.jsx)("a", { href: "#", className: "text-sm text-gray-600 transition-colors hover:text-gray-900", children: "Pol\u00EDtica de Privacidad" }), (0, jsx_runtime_1.jsx)("a", { href: "#", className: "text-sm text-gray-600 transition-colors hover:text-gray-900", children: "T\u00E9rminos de Servicio" }), (0, jsx_runtime_1.jsx)("a", { href: "#", className: "text-sm text-gray-600 transition-colors hover:text-gray-900", children: "Soporte" })] })] }) })] }));
}
//# sourceMappingURL=footer.js.map