DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_READONLY_USER}') THEN
    CREATE ROLE ${POSTGRES_READONLY_USER} LOGIN PASSWORD '${POSTGRES_READONLY_PASSWORD}';
  END IF;
END $$;
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READONLY_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_READONLY_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READONLY_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_READONLY_USER};