name: Visual Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/design-system/**'
      - 'apps/**/components/**'
      - '!**.md'
  push:
    branches:
      - main
      - develop

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm --filter @a4co/design-system exec playwright install --with-deps

      - name: Build Design System
        run: pnpm --filter @a4co/design-system build

      - name: Run Playwright tests
        run: pnpm --filter @a4co/design-system exec playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: packages/design-system/playwright-report/
          retention-days: 30

  percy-snapshots:
    runs-on: ubuntu-latest
    name: Percy Visual Tests
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm --filter @a4co/design-system build-storybook

      - name: Percy Snapshots
        run: |
          pnpm add -g @percy/cli @percy/storybook
          percy storybook ./packages/design-system/storybook-static
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  component-screenshot-tests:
    runs-on: ubuntu-latest
    name: Component Screenshot Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run component tests
        run: pnpm --filter @a4co/design-system test:visual

      - name: Upload snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff-snapshots
          path: packages/design-system/**/__diff_output__/

  merge-reports:
    needs: [visual-tests]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          merge-multiple: true

      - name: Merge reports
        run: |
          npm i -g @playwright/test
          playwright merge-reports --reporter html ./playwright-report

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30